---
output: html_document
---

```{r, include = FALSE}
library(tidyverse)
library(stpR)

options(htmlwidgets.TOJSON_ARGS = list(na = "string")) # option_chunk$set did not work, ideas why?

stp_object <- readRDS(file.path("/Users/ryanweber/Desktop/Data Setup Package/stpR", "secure_data/2023_01_01/stp_ob.rds"))

reporting_object <- get_reporting_cases(stp_object,
                                        limit_to_highlight = FALSE,
                                        limit_to_issue = FALSE)
```

## trt

trt notes...

```{r, echo = FALSE}
ref_ob <- reporting_object %>%
slice(1) %>%
.[["ref_ob"]] %>%
.[[1]]

if (!is.null(ref_ob)) {
  if (nrow(ref_ob) <= 10) {

    ref_ob %>%
      DT::datatable(rownames = FALSE,
                    options = list(dom = "t"))

  } else {

    ref_ob %>%
      DT::datatable(rownames = FALSE)

  }
}
```

## age

age notes...

```{r, echo = FALSE}
ref_ob <- reporting_object %>%
slice(2) %>%
.[["ref_ob"]] %>%
.[[1]]

if (!is.null(ref_ob)) {
  if (nrow(ref_ob) <= 10) {

    ref_ob %>%
      DT::datatable(rownames = FALSE,
                    options = list(dom = "t"))

  } else {

    ref_ob %>%
      DT::datatable(rownames = FALSE)

  }
}
```

## comp_approach_asa

summary proc, ASA notes

```{r, echo = FALSE}
ref_ob <- reporting_object %>%
slice(3) %>%
.[["ref_ob"]] %>%
.[[1]]

if (!is.null(ref_ob)) {
  if (nrow(ref_ob) <= 10) {

    ref_ob %>%
      DT::datatable(rownames = FALSE,
                    options = list(dom = "t"))

  } else {

    ref_ob %>%
      DT::datatable(rownames = FALSE)

  }
}
```

## age_filter

Remove patients younger than 18 years old

```{r, echo = FALSE}
ref_ob <- reporting_object %>%
slice(4) %>%
.[["ref_ob"]] %>%
.[[1]]

if (!is.null(ref_ob)) {
  if (nrow(ref_ob) <= 10) {

    ref_ob %>%
      DT::datatable(rownames = FALSE,
                    options = list(dom = "t"))

  } else {

    ref_ob %>%
      DT::datatable(rownames = FALSE)

  }
}
```
