---
output: html_document
params:
  stp_ob: ""
  report_type: ""
  child_rmd_path: ""
---

```{r, include=FALSE}
library(tidyverse)

options(htmlwidgets.TOJSON_ARGS = list(na = 'string')) # option_chunk$set didn't work, ideas why?
```

``` {r, include=FALSE, echo=FALSE}

out <- NULL

# TODO: add so much params checking, particularly that stp_ob is a dataframe object and that there exists rows to display



mapping
 - highlight
 - issue
 - report
 (map_ob, update_ob)

filtered
 - highlight
 - issue
 - report
 (filter_ob, update_ob)

Header
Description (now just notes)
Object

output_ob <- stp_ob %>%
  filter()

for (i in seq_along(params$ref_yaml)){
  
  
  # TEMP: would have different system/utilize params for default versions
  child_ver <- 1
  
  if (!is.null(params$ref_yaml[[i]]$child_version))
    child_ver <- params$ref_yaml[[i]]$child_version
  
  out <- c(out,
           knitr::knit_child('{params$child_rmd_path}/{params$ref_yaml[[i]]$type}_{child_ver}.Rmd' %>% glue::glue()))

}

```

`r paste(out, collapse='<br><br>')`
